local_models:
  path: wonder_local.model.local_models.local_models
  object_method: true

hf_get:
  path: wonder_local.util.hf_get.hf_get
  object_method: true

sigils:
  path: wonder_local.util.sigils.sigils
  object_method: true

sigil_profile:
  path: wonder_local.util.sigil_profile.sigil_profile
  object_method: true

sigil_profile_all:
  path: wonder_local.util.sigil_profile.sigil_profile_all
  object_method: true

load_model:
  path: wonder_local.model.load_model.load_model
  object_method: true
  default_model: "microsoft/phi-2"

generate:
  path: wonder_local.model.generate.generate
  object_method: true
  requires:
    - estimate
    - load_model

llama_generate:
  path: wonder_local.llama.llama_generate.llama_generate
  object_method: true

train:
  path: wonder_local.model.train.train
  object_method: true
  requires:
    - load_model
  default_model: "meta-llama/Meta-Llama-3-8B-Instruct"

estimate:
  path: wonder_local.util.estimation.generate_estimated
  object_method: false

mpstest:
  path: wonder_local.util.mpstest.mpstest
  object_method: true

wonder_generate:
  path: wonder_local.rlhf.wonder_generate.wonder_generate
  object_method: true
  requires:
    - load_model
    - estimate

md_to_questions:
  path: wonder_local.rlhf.md_to_questions.md_to_questions
  object_method: true
  requires:
    - estimate

wonder_repl:
  path: wonder_local.repl.wonder_repl.wonder_repl
  object_method: true
  requires:
    - load_model
    - estimate

llama_repl:
  path: wonder_local.repl.llama_repl.llama_repl
  object_method: true
  llamalike: true
