local_models:
  path: wonder_local.model.local_models.local_models
  object_method: true

hf_get:
  path: wonder_local.util.hf_get.hf_get
  object_method: true

sigils:
  path: wonder_local.util.sigils.sigils
  object_method: true

sigil_profile:
  path: wonder_local.util.sigil_profile.sigil_profile
  object_method: true

sigil_profile_all:
  path: wonder_local.util.sigil_profile.sigil_profile_all
  object_method: true

find_missing_signatures:
  path: wonder_local.util.sigil_profile.find_missing_signatures
  object_method: true

fix_missing_signatures:
  path: wonder_local.util.sigil_profile.fix_missing_signatures
  object_method: true

load_signatures:
  path: wonder_local.rlhf.signature_review.load_signatures
  object_method: true

report_missing_rarity:
  path: wonder_local.rlhf.signature_review.report_missing_rarity
  object_method: true

load_model:
  path: wonder_local.model.load_model.load_model
  object_method: true
  default_model: "microsoft/phi-2"

run_tests:
  path: wonder_local.test.run_tests.run_tests
  object_method: true

generate:
  path: wonder_local.model.generate.generate
  object_method: true
  requires:
    - estimate
    - load_model
  tests:
    - input: "what is the capital of france?"
      expected: "Paris"
    - input: "how many legs does a dog have?"
      expected: "4"

llama_generate:
  path: wonder_local.llama.llama_generate.llama_generate
  object_method: true

train:
  path: wonder_local.model.train.train
  object_method: true
  requires:
    - load_model
  default_model: "meta-llama/Meta-Llama-3-8B-Instruct"

estimate:
  path: wonder_local.util.estimation.generate_estimated
  object_method: false

mpstest:
  path: wonder_local.util.mpstest.mpstest
  object_method: true

wonder_generate:
  path: wonder_local.rlhf.wonder_generate.wonder_generate
  object_method: true
  requires:
    - load_model
    - estimate

md_to_questions:
  path: wonder_local.rlhf.md_to_questions.md_to_questions
  object_method: true
  requires:
    - estimate

md_to_questions_all:
  path: wonder_local.rlhf.md_to_questions.md_to_questions_all
  object_method: true
  requires:
    - estimate

basic_repl:
  path: wonder_local.repl.basic.repl
  object_method: true

rlhf_repl:
  path: wonder_local.rlhf.repl.rlhf_repl
  object_method: true

wonder_repl:
  path: wonder_local.repl.wonder_repl.wonder_repl
  object_method: true
  requires:
    - load_model
    - estimate

llama_repl:
  path: wonder_local.repl.llama_repl.llama_repl
  object_method: true
  llamalike: true
